services:
  fastapi_app:
    build: .
    container_name: brews_express_backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - "/home/lopsig/proyectos/brews_express/brews_express_backend:/app"
    environment:
      MongoDB_URI: mongodb+srv://jonathanlstrabajo:7l0CYhHLnUpOEEWt@cluster0.bf7bwoa.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      JWT_SECRET_KEY: secret123
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

